### ISSUE TITLE
File origin does not match the viewer's

### ISSUE THREAD

**Issue by JulianElwood** [TwisterMc/pdfjs-viewer-shortcode#6]
I get this error with any pdf I try to display.
I have media settings option to store media by year and date switched on - Is this causing the error with loading the pdf?
Only threads I see on the web seem to imply I either need to:

Set HOSTED_VIEWER_ORIGINS_OPTIONS - I don't know where to set this or what format is needed

Comment out code for this message - I feel this is unsafe and I don't want to change plug in code in any way

Please help resolve this for me

**Comment by TwisterMc** [comment]
Do you have a URL I could look at?

Are you using a VPN? If so, that might be causing the issue.

**Comment by JulianElwood** [comment]
My site is not live yet as we are still in final stages of setting it up.  If you want me to put it live for a few minutes (while we are on a call together) so you see the issue then please let me know the time that suits you and what number I should call you on.
I am not using a VPN as these are illegal in China (as we are setting up a China company that will depend on Ministry approval for our on line activities I want to ensure full compliance with all local laws.)
Julian

**Comment by JulianElwood** [comment]
I see the following code against the block for a pdf viewer:


<div class="wp-block-pdfjsblock-pdfjs-embed pdfjs-wrapper">[pdfjs-viewer viewer_width=0 viewer_height=300 url=https://safetystock.guru/wp-content/uploads/2020/08/YBL_Inventory_Optimization_Performance_Product_Brief_1.0_EN.pdf download=true print=true fullscreen=true fullscreen_text="View%20Fullscreen" zoom=auto ]</div>


Hope this helps,
Regards

Julian

**Comment by TwisterMc** [comment]
Sorry. I didn't mean VPN, I meant CDN. 🤦‍♂️

The PDF has to load from the same URL as the the site is loading from. If the PDF is offloaded to a CDN, then the URLs won't match.

**Comment by JulianElwood** [comment]
Hi
I must be doing something wrong that should hopefully be easy to fix!!
The pdf is in my media library on the same site as the web pages which malfunction.
Regards

Julian

**Comment by TwisterMc** [comment]
If you add a PDF to a page, and have the 'Fullscreen' link enabled, can you view the post, hit the 'Fullscreen' link and then paste that link here? It doesn't need to be accessible to me, but I want to see what it looks like. 

Example: 
`https://olaf.local/wp-content/plugins/pdfjs-viewer-shortcode/pdfjs/web/viewer.php?file=https%3A%2F%2Folaf.local%2Fwp-content%2Fuploads%2F2020%2F03%2F7700.pdf&dButton=true&pButton=true&oButton=false&v=1.5.1#zoom=auto`

**Comment by JulianElwood** [comment]
Hi,
Sorry for delayed reply – I have checked this and the link appears to have the right address in the media library as in attachment.
Hope this helps as I would really like to get your plug in working – it seems to have the best functionality for what I need to do!
Regards
Julian

**Comment by JulianElwood** [comment]
Hi,
I also have a Chinese site and was testing pdf plugs for that.  I could not get PDFjs Viewer with the wordpress version on the Aliyun server and tried another plug in which worked ok (but did not work when I tried it on my international site hosted by Godaddy).
Could be there is some strange error using your plug in that is to do with my location (but I’m not sure as people in UK have tested my site and also get the error!)
Regards,

Julian

**Comment by TwisterMc** [comment]
Can either of you provide me the link the Fullscreen link is going to?

**Comment by JulianElwood** [comment]
Hi,

The full screen link was in a word doc attached to a previous email… it is

Link in media library…
https://safetystock.guru/wp-content/uploads/2020/08/YBL_MRP_Training_Tool_Product_Brief_1.0_EN.pdf
Click on View Fullscreen reveals same path…
https://bmv.6ec.myftpupload.com/wp-content/plugins/pdfjs-viewer-shortcode/pdfjs/web/viewer.php?file=https://safetystock.guru/wp-content/uploads/2020/08/YBL_MRP_Training_Tool_Product_Brief_1.0_EN.pdf&dButton=true&pButton=true&oButton=false&v=1.5.1#zoom=auto

I have put my site live now and cannot test changes for a few days until I have a test site up and running.  Still keen to see if this plug in can work for me as my workaround is not very good.

Regards

Julian

**Comment by TwisterMc** [comment]
The issue is you can't have two different domains. You can only load PDFs from the same domain that the plugin is running on. 

<img width="862" alt="domain-issue" src="https://user-images.githubusercontent.com/46997/90350856-f9482500-e003-11ea-8dcf-57fdd5d3101f.png">

**Comment by JulianElwood** [comment]
Sorry to disagree but the plug in and the pdf are on the same domain!
From my point of view the best way forward is to use a different plug in so I will not need a resolution to this,
Regards
Julian

**Comment by TwisterMc** [comment]
As pointed out in the screenshot, it's reporting to different domains. It could be because it's on a staging site and the uploads are still pointing to production, or it could be that something is configured differently, but the plugin and media domain is different. They may technically be the same domain, but they have different addresses.

**Comment by TwisterMc** [comment]
Try the latest version and see if that helps any.

**Comment by Catra-chordeon** [comment]
Using Version: 1.5.7 (as in PlugIn library)/v2.3.200   on WordPress version 5.6 and having the same problem.  
Black/blank pdf viewwer shows following error message:   PDF.js v2.3.200 (build: 4ae3f9fc)
Message: file origin does not match viewer's

the two pdf files I am trying to display or download are IN my media library, not linked to it.  I'm using a more current version than JulianE above.  BUT, i AM on a staging site.  Thing is,  the urls of the media library items have the staging site location incorporated into them.  What do i do?

**Comment by TwisterMc** [comment]
Do you have a URL? This issue happens when the PDF is coming from a URL that is not the same as the URL that is showing the PDF.

**Comment by rmykolas** [comment]
Hi there @TwisterMc, I had the same issue, but I fixed it by adding a list of CDN links to var HOSTED_VIEWER_ORIGINS within the viewer.js file.

But for some reason, this hack does not work with the 1.5.9 version of the plugin. Would you mind updating the repo to see what's changed in the plugin and could be causing this?

Thanks!

**Comment by cappypopp** [comment]
Is there any way to update the HOSTED_VIEWER_ORIGINS via the plugin or do I have to edit it manually? I have PDFs hosted in a CRM that I need to embed on a landing page on a WordPress site. They need to remain in the CRM for tracking reasons, and I don't want to duplicate them by having to upload them to the WP Media Library or my server somewhere. I updated my site CSP to allow framing content from my CRM host domains but it doesn't matter because I get:

```
app.js:2165 Uncaught (in promise) Error: file origin does not match viewer's
    at validateFileURL (app.js:2165:15)
    at Object.run (app.js:650:7)
```
